server:
  port: 11000

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.0.0.128:3306/gulimall_wms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-ware

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # 这里添加扫描.xml的配置文件
  global-config:
    db-config:
      id-type: auto # 这里配置主键规则